In [3]:
"""
[簡答題] 
#1請問下列這三種方法有什麼不同？
print(a.sum())
print(np.sum(a))
print(sum(a)) 
#2請對一個 5x5 的隨機矩陣作正規化的操作。
#3請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。
"""
import numpy as np
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

print(english_score.sum())
print(np.sum(english_score))
print(sum(english_score)) 

## 一樣 都是 '加總'
"""
sum()為python內建的函式
a.sum()和np.sum(a)為陣列才有的
定義在np或是array下
"""


403
403
403


In [20]:
#2請對一個 5x5 的隨機矩陣作正規化的操作。
"""
複習數學:
正規矩陣: A*A' = A'*A

常見的數據歸一化方法
min-max標準化(Min-max normalization)/0-1標準化(0-1 normalization)
也叫離差標準化，是對原始數據的線性變換，使結果落到[0,1]區間，轉換函數如下

X' = (x-min) / max-min
"""

#normalization
B = np.random.rand(5,5)
q2=B*10+10 #
print(q2)
q2_max = np.max(q2)
q2_min = np.min(q2)

q2_normalization = (q2 - q2_min)/(q2_max - q2_min)
print(q2_normalization)

[[12.51449034 16.20934102 12.72832439 19.74382457 16.91188564]
 [19.28038361 11.96101914 16.63425371 19.95213363 14.89793594]
 [10.40656875 15.49022017 13.75913699 16.97908716 14.59101655]
 [18.14242052 13.38026547 15.05964261 14.10896574 12.25272271]
 [15.77441482 12.28089363 18.77313097 17.24619888 19.53722162]]
[[0.22082733 0.60790245 0.24322873 0.9781774  0.68150151]
 [0.929627   0.1628453  0.6524166  1.         0.47051874]
 [0.         0.53256685 0.35121738 0.68854159 0.43836565]
 [0.8104132  0.31152653 0.48745925 0.38786568 0.19340437]
 [0.56233928 0.19635558 0.87648686 0.7165244  0.95653353]]


In [139]:
#3請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1
A = np.random.randint(1,10,10)
print(A)
MAX_A = np.max(A) #這個是值
MAX_A_where= np.argmax(A) #這個是索引
print(MAX_A)
print(MAX_A_where) #means 第幾個

ANS=[]
for i in A:
    if i >= MAX_A:
        ANS.append(i)
        A[MAX_A_where]=-1

print('ANS:', ANS)
print('正確答案:', A)

[3 1 2 3 6 7 7 9 5 4]
9
7
ANS: [9]
正確答案: [ 3  1  2  3  6  7  7 -1  5  4]
