In [17]:
"""
D02 進階題
作業目標
熟悉陣列維度轉換，並且會擷取需要資料
作業重點
使用reshap須注意order用法
where可以運用邏輯條件擷取資料

題目:
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
2.呈上題的array，找出被6除餘1的數的索引

#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))

#2.呈上題的array，找出被6除餘1的數的 "索引"
"""

'\nD02 進階題\n作業目標\n熟悉陣列維度轉換，並且會擷取需要資料\n作業重點\n使用reshap須注意order用法\nwhere可以運用邏輯條件擷取資料\n\n題目:\n1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")\n2.呈上題的array，找出被6除餘1的數的索引\n\n#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")\narray1 = np.array(range(30))\n\n#2.呈上題的array，找出被6除餘1的數的索引\n'

In [18]:
import numpy as np

array1 = np.array (range(30))
print(array1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [19]:
# key: C 的意義是 C-style，展開時是以 row 為主的順序展開；而 F 是 Fortran-style，展開時是以 column 為主的順序展開

array2 = array1.reshape((5, 6), order = "F") # F 是 Fortran-style，展開時是以 column 為主的順序展開
print(array2)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [20]:
array3 = array2.flatten() #變成扁平一維的 xdd
print(array3)


[ 0  5 10 15 20 25  1  6 11 16 21 26  2  7 12 17 22 27  3  8 13 18 23 28
  4  9 14 19 24 29]


In [25]:
"""
# 排序的語法
# 要對陣列進行排序可以使用 sort() 與 argsort()，
# 兩者的差異是在 sort() 回傳的是排序後的陣列，而 argsort() 回傳的是排序後的陣列索引值。
numpy.sort(a, axis=-1, kind=None, order=None)	ndarray.sort()
numpy.argsort(a, axis=-1, kind=None, order=None)	ndarray.argsort()

np.random.seed(3)
a = np.random.randint(0, 20, 10)
a
np.sort(a)
a.argsort()
a.sort()
a
"""
array4 = np.sort(array3)
print(array4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [21]:
# 5.3 找出符合條件的元素：
# 語法： numpy.where(condition[, x, y])
# 題目: #2.呈上題的array，找出被6除餘1的數的索引

np.where (array2%6 == 1)
# 記得要一起看, array2 的 [0,5]=25, [1,0]=1
# 所以這個方法是找出 "索引" 而非 "索引的值"

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))

In [23]:
np.where (array3%6 ==1) # %就是餘數的
# 是指這個陣列的 所以 5 是25

(array([ 5,  6, 13, 20, 27], dtype=int64),)

In [26]:
np.where (array4%6 ==1)
# 所以會發現有排列真的比較容易看

(array([ 1,  7, 13, 19, 25], dtype=int64),)