In [24]:
"""
1. [簡答題] 請問下列程式碼，運算結果分別為何？

a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？
3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？
"""

#Q1 [簡答題] 請問下列程式碼，運算結果分別為何？

import numpy as np
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
print(a)
print(b)
print(c)
print(d)
print(e)

[20 30 40 50]
[1 2 3 4]
1
[1]
[1 2]


In [25]:
print(a + a)
print(a + b)
print(a + c)
print(a + d)
# print(a + e)  # 不符合Boardcast原則

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


In [26]:
# Q2: 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

A = np.ones(3)*1
B = np.ones(3)*2
print(A)
print(B)

[1. 1. 1.]
[2. 2. 2.]


In [27]:
#不用迴圈
C = (A+B)*(-A/2)
print(C)

[-1.5 -1.5 -1.5]


In [28]:
#用迴圈
"""
語法
a = [20, 30, 40, 50]
b = []
for i in a:
  b.append(i+1)
print(b)
# [21, 31, 41, 51]
"""
A = np.ones(3)*1
print(A)

ANS = []
for i in np.arange(A.size):
    ANS.append((A[i] + B[i])* (-A[i]/2))

print(ANS)


[1. 1. 1.]
[-1.5, -1.5, -1.5]


In [29]:
# Q3: 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？
A = np.ones((1,6))
B = np.ones((6,1))
print(A * B) # 外積
print(np.outer(A, B))# 外積

print(np.dot(A, B)) # 內積
print(A @ B) # 內積

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
[[6.]]
