In [3]:
!pip3 install numpy 

#安裝 NumPy
"""安裝Numpy 可以用
1) !pip install numpy
2) !pip3 install numpy
3) 在 Anaconda 環境下的話, 執行 conda install numpy
"""
import numpy as np # 載入 NumPy
np.__version__ #目前安裝的 NumPy 版本

'1.19.2'

In [4]:
# 題目 1.生成一個等差數列，首數為0，尾數為20，公差為1的數列

"""
語法: 產生陣列
nump.linspace (start, stop, num=50, endpoint=True, reestep=False, dtype='None', axis=0)
endpoint: 就是要不要有包含最後 stop 的值
restep: 就是要不要顯示間隔值的值
dtype =int8,int16, int32, int64, float16, float32, float64, float128
"""

Q01 = np.linspace (0,20,num=21, endpoint=True, dtype='int64')
print(Q01)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
# 題目 2.呈上題，將以上數列取出偶數

"""
語法: NumPy 陣列的索引和切片(就是找出來), Slicing
[start:stop:step]
step就是間隔值
"""

Q01[::2] #p.s. 如果start和stop值都沒有給 → 就是都取出


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int64)

In [7]:
# 題目 3.呈1題，將數列取出3的倍數。

"""
語法: NumPy 陣列的索引和切片(就是找出來), Slicing
[start:stop:step]
step就是間隔值
"""

Q01[3::3]

array([ 3,  6,  9, 12, 15, 18], dtype=int64)