In [1]:
import numpy as np

"""
D03 HW-BASIC
1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？
2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。
"""


'\nD03 HW-BASIC\n1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？\n2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。\n3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。\n'

In [10]:
# 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

a = np.zeros((4,6), dtype='float64')
b = np.empty((3,5), dtype='float64')
print('a:', a)
print('b:', b)

"""
如果想要產稱一個由 0 所組成的矩陣，可以使用 np.zeors(...) 的方法。除此之外，在文件中有另外一個類似的方法是 np.empty(...)：
呼叫 zeros()、ones() 函式，可以依照傳入的形狀引數，建立元素全為 0、全為 1 的陣列。
使用 empty() 函式則是不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定。
"""
c=np.empty((2,3), dtype='float64')
print('c:', c)

"""
#empty會建立很接近0的數值, zeros會建立0的數值
#empty必須讓使用者輸入數值，zeros是建立可以使用的0在array

np.zeros((2, 3)) 會產生真正的 0；np.empty((2, 3)) 會產生一個近似於 0 的陣列。
np.empty 可以用於只是想要初始化，但之後就會數值覆寫過的形況。
"""

a: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
b: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
c: [[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# Q2: 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

#另外一種常見的情境是產生一組固定大小的亂數：
"""
from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2))
random = rng.random((3,2))
integers = rng.integers(0, 10, size=(3,2))
"""

from numpy.random import default_rng
rng = default_rng()

d = rng.random ((6,4))
e = rng.standard_normal((6,4))
f = rng.integers(low=3, high=7, size=(2,3))
                   
print(d)
print(e)
print(f)

# 4捨5入的辦法
# (np.round(a))
g = np.round(d)
print('g_integer:', g)



[[0.22952706 0.79933045 0.3005306  0.13386155]
 [0.70258382 0.9542244  0.97645381 0.00432415]
 [0.77117549 0.62852443 0.5584049  0.93446467]
 [0.41445057 0.51580108 0.38614995 0.32436828]
 [0.221765   0.63057163 0.75953171 0.61924534]
 [0.7314911  0.53765    0.21350504 0.8315122 ]]
[[-4.95427157e-01 -2.49635157e-01 -1.63299434e-01  4.68941870e-02]
 [ 1.71747685e+00 -7.49074195e-01  8.86793826e-01  2.20504178e+00]
 [ 6.15676645e-01 -1.51414039e+00  6.24780876e-02 -1.09742842e+00]
 [-1.58207589e-01  6.57957104e-01  1.77527813e+00  1.20012491e+00]
 [-1.26042198e+00 -1.19813217e-04 -1.73676999e-01 -1.11732323e+00]
 [ 4.81363601e-01  4.84964310e-01 -9.76513918e-01 -2.21546119e+00]]
[[4 4 3]
 [5 3 6]]
g_integer: [[0. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [0. 1. 0. 0.]
 [0. 1. 1. 1.]
 [1. 1. 0. 1.]]


In [29]:
"""
np.around 四舍五入
np.around 返回四舍五入后的值，可指定精度。
around(a, decimals=0, out=None)

np.floor 向下取整
np.floor 返回不大于输入参数的最大整数。 即对于输入值 x ，将返回最大的整数 i ，使得 i <= x。 
注意在Python中，向下取整总是从 0 舍入。

np.ceil 向上取整
np.ceil 函数返回输入值的上限，即对于输入 x ，返回最小的整数 i ，使得 i> = x。

np.where 条件选取
numpy.where(condition[, x, y])
根据条件 condition 从 x 和 y 中选择元素，当 condition 为 True 时，选 x，否则选 y。

"""
print(d)
print(d*100)
print(np.floor(d*100))

[[0.22952706 0.79933045 0.3005306  0.13386155]
 [0.70258382 0.9542244  0.97645381 0.00432415]
 [0.77117549 0.62852443 0.5584049  0.93446467]
 [0.41445057 0.51580108 0.38614995 0.32436828]
 [0.221765   0.63057163 0.75953171 0.61924534]
 [0.7314911  0.53765    0.21350504 0.8315122 ]]
[[22.9527062  79.93304531 30.05305966 13.38615496]
 [70.25838211 95.42244001 97.64538115  0.43241457]
 [77.11754906 62.85244273 55.84048976 93.44646727]
 [41.44505733 51.58010761 38.61499479 32.43682821]
 [22.17650004 63.05716252 75.95317076 61.92453368]
 [73.14911005 53.76499993 21.35050377 83.15121961]]
[[22. 79. 30. 13.]
 [70. 95. 97.  0.]
 [77. 62. 55. 93.]
 [41. 51. 38. 32.]
 [22. 63. 75. 61.]
 [73. 53. 21. 83.]]


In [33]:
# Q3: 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

m = 30
n = 40

h = np.random.rand (4,6)
print ('h:', h)
i = m+h*(n-m)
print ('i:', i)

h: [[0.95048676 0.86341557 0.10904412 0.96676993 0.34456626 0.0549241 ]
 [0.79954921 0.32998161 0.47237834 0.52394734 0.0887831  0.75121965]
 [0.06007683 0.14814505 0.15207076 0.1545675  0.27581948 0.53378412]
 [0.59346579 0.24596516 0.14259507 0.89201369 0.92388428 0.26968969]]
i: [[39.50486755 38.63415573 31.09044122 39.66769934 33.44566257 30.54924097]
 [37.99549214 33.29981613 34.72378337 35.23947339 30.887831   37.51219652]
 [30.60076829 31.48145045 31.5207076  31.545675   32.75819477 35.33784125]
 [35.9346579  32.45965157 31.42595074 38.92013687 39.23884281 32.69689693]]
