In [ ]:
# NumPy 陣列的算術運算
# 就是數學的矩陣運算

"""
import numpy as np

a = np.array( [20,30,40,50] )
b = np.arange( 4 )

print(a + b)
# [20 31 42 53]
print(a * b)
# [ 0 30 80 150]


import numpy as np

a = np.array( [20,30,40,50] )

print(a - 2)
# [18 28 38 48]
print(a / 10)
# [2. 3. 4. 5.]

import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

print(data + ones_row)
# array([[2, 3],
#        [4, 5],
#        [6, 7]])


a = np.array( [20,30,40,50] )
print(a + 1)
# array([21 31 41 51])

a = [20, 30, 40, 50]
b = []
for i in a:
  b.append(i+1)
print(b)
# [21, 31, 41, 51]


import numpy as np

a = np.array([[1.0, 2.0], [3.0, 4.0]])
# [[1. 2.]
#  [3. 4.]]
y = np.array([[5.], [7.]])
# [[5.]]
#  [7.]]

a.transpose()
# array([[1., 3.],
#        [2., 4.]])
np.linalg.inv(a)
# array([[-2. ,  1. ],
#        [ 1.5, -0.5]])
np.trace(u)
# 2.0
np.linalg.solve(a, y)
# array([[-3.],
#        [ 4.]])
"""

#NumPy 陣列運算 – 平方根 np.sqrt()
"""
np.sqrt(4)
np.sqrt(a)
"""

#NumPy 陣列運算 – 歐拉數 (Euler's number) 及指數函式 np.exp()
"""
np.e
np.exp(1)
np.exp(np.arange(5))
"""

#NumPy 陣列運算 – 對數函式
"""
np.log(9)/np.log(3)
"""

#NumPy 陣列運算 – 取近似值
#NumPy 陣列運算 – 取絕對值：np.abs(), np.absolute(), np.fabs()
#NumPy 陣列運算 – 點積 (dot product)
